name: 'Cache Cypress'
description: 'Cache the Cypress cache folder'
inputs:
  file-to-hash:
    description: 'file that will be hashed to determine if the cache is hit'
    required: false
    default: '**/yarn.lock'
runs:
  using: 'composite'
  steps:
    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: '~/.cache/Cypress'
        key: ${{ runner.os }}-cypress-cache-${{ hashFiles(inputs.file-to-hash) }}
