name: 'yarn install'
description: 'Cache node_modules + the yarn store and install & execute yarn install'
inputs:
  node-version:
    description: 'node version to use'
    required: false
    default: '14'
outputs:
  node-modules-cache-hit:
    description: "returns whether the node_modules cash was hit"
    value: ${{ steps.cache-node-modules.outputs.cache-hit }}
runs:
  using: 'composite'
  steps:
    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Install yarn and cache store
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install --frozen-lockfile --prefer-offline
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
