name: 'Install dependencies with Pnpm'
description: 'Cache the pnpm store and install & execute pnpm install'
inputs:
  pnpm-version:
    description: 'pnpnm version to use'
    required: false
    default: 6.32.3
runs:
  using: 'composite'
  steps:
    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-
    - name: Install and execute pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: |
          - args: [--frozen-lockfile, --prefer-offline]
